### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tarkiin** [DanDev95/DiscordAccountExporter#1]
file:///C:/Users/user/Downloads/DiscordAccountExporter-master/DiscordAccountExporter-master/wrappers/getChannelMessages.js:37
  let lastMessage = data.slice(-1)[0].id;
                                     ^

TypeError: Cannot read properties of undefined (reading 'id')
    at getChannelMessages (file:///C:/Users/user/Downloads/DiscordAccountExporter-master/DiscordAccountExporter-master/wrappers/getChannelMessages.js:37:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exportAllDms (file:///C:/Users/user/Downloads/DiscordAccountExporter-master/DiscordAccountExporter-master/app.js:15:20)

**Comment by nostorian** [comment]
the owner is a fucking 9yr old skid, dont expect anything to work, he prolly skids some random old shit from internet and sells it

**Comment by cipherwithadot** [comment]
:o
